language: java
sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk7
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk7
    - os: osx
      osx_image: xcode8.3 # OS X 10.12
    - os: osx
      osx_image: xcode7.3 # OS X 10.11
    - os: osx
      osx_image: xcode6.4 # OS X 10.10

after_success:
  - mvn clean test cobertura:cobertura coveralls:cobertura
