language: java

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.1 # OSX 10.12, Oracle Java 8

# The 'build' task runs most things, including test, check, & static analysis
install: true
script: ./gradlew -u -S --no-daemon --no-parallel build jacocoAggregateReport coveralls

cache:
  directories:
    - $HOME/.npm/
    - $HOME/.gradle/
