language: java

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
      osx_image: xcode9.2 # OSX 10.12, Oracle Java 8
      script: ./gradlew -u -S --no-daemon --no-parallel build
  include:
    - os: osx
      osx_image: xcode9.2 # OSX 10.12, Oracle Java 8
      script: ./gradlew -u -S --no-daemon --no-parallel build
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8

# The 'build' task runs most things, including test, check, & static analysis
install: true
script: ./gradlew -u -S --no-daemon --no-parallel build jacocoAggregateReport coveralls

cache:
  directories:
    - $HOME/.npm/
    - $HOME/.gradle/
