version: '{build} ({branch})'
skip_tags: true
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
test_script:
  - mvn clean test -V -B
cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
